- name: Crea Instancia Autonomous Database Allways Free
  hosts: localhost
  connection: local

  vars_files: vault.yaml


  tasks:
    - block:
        - name: Crea ADB (Always Free)
          oracle.oci.oci_database_autonomous_database:
              compartment_id: "{{ compartment_ocid }}"
              cpu_core_count: "{{ cpu_core_count }}"
              display_name: "{{ display_name }}"
              admin_password: "{{ admin_password }}"
              db_name: "{{ db_name }}"
              data_storage_size_in_gbs: "{{ data_storage_size_in_gbs }}"
              is_free_tier: true
              state: 'present'
          register: resultado

        - set_fact:
             autonomous_database_id: "{{ resultado.autonomous_database.id }}"

        - assert:
            that:
              - resultado.autonomous_database.lifecycle_state == "AVAILABLE"

        - name: Lista Todas las Instancias de ADB
          oracle.oci.oci_database_autonomous_database_facts:
             compartment_id: "{{ compartment_ocid }}"
             display_name: "{{ display_name }}"
          register: resultado

        - name: Valida si Existe Nueva Instancia
          assert:
             that:
                - resultado.autonomous_databases[0].display_name == display_name
      rescue:

        - fail:
            msg: "ERROR, No se logro Crear Instancia ADB."
